import './globals.css'
import './assets/css/tailwind.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-layout-mode="light">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
